# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbb2fadd6770728aea9d2bf13735ff0542a8062691ccd730f6223214cea9e9c958e91a813000ac5dac7d3f405d1e3363e3374fe2ea6f1027bdb8616c160fb866

test:
  secret_key_base: 11822200f1ffe185be8b53233e1db513cee07b9531fc5069a9e5ca5fdf18e0da7422db112f6dade8f99e18b8da4b48ea1e5c9967f15bfe219b52d81e09e875ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
